version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval:
        cron: "14 3 * * 3"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval:
        cron: "14 3 * * 3"
    open-pull-requests-limit: 10

